title: Alexandra Barbu
#logo: docs/assets/headshot_circle.png
description: Junior Frontend Developer | Corporate Relationship Manager | Outdoor Enthusiast
#show_downloads: true
theme: jekyll-theme-minimal
